### ISSUE TITLE
Script does not output error codes even if I run it on a cpu instance.

### ISSUE THREAD

**Issue by keisuke-umezawa** [chainer/google-colaboratory#5]
# Phenomenon

On a cpu instance in colaboratory, we can not see error codes.
![2018-12-27 14 31 03](https://user-images.githubusercontent.com/1277089/50467205-2c7c1180-09e5-11e9-8640-827998082d91.png)

# Reason
we can run `nvidia-smi` on cpu instances, so we cannot judge it cpu or gpu.

https://github.com/chainer/google-colaboratory/blob/master/docs/install#L9-L17

**Comment by aYasukiIkeuchi** [comment]
I investigated. My idea is just replace `if ! which nvidia-smi > /dev/null; then` to `if nvidia-smi | grep -q "Make sure that the latest NVIDIA driver is installed"; then`.
The root cause of this issue is the new container image has nvidia-smi binary even though using cpu instance.

Trial code.
https://colab.research.google.com/drive/1JsOB-eu5Upzlv8Co-STaGrb4cN0L6GWD

**Comment by kmaehashi** [comment]
Thanks, made a PR.
`nvidia-smi` exits with status code 9 along with the message `Make sure that the latest NVIDIA driver is installed` when it is invoked in CPU/TPU instances.
